"""updated user preference

Revision ID: 036c62740eb6
Revises: 8c6153108be0
Create Date: 2025-07-07 17:35:36.755835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036c62740eb6'
down_revision = '8c6153108be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('willing_to_mentor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('founder_interests', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('investor_interests', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('investor_interests')
        batch_op.drop_column('founder_interests')
        batch_op.drop_column('willing_to_mentor')

    # ### end Alembic commands ###
