"""add resume and related tables

Revision ID: 4001dd77727b
Revises: c930d5d4bd8e
Create Date: 2025-06-20 15:43:29.466287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4001dd77727b'
down_revision = 'c930d5d4bd8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('resume_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
