"""Add onboarding fields to user preferences

Revision ID: 558c582c12c9
Revises: 9ed064cdf4f6
Create Date: 2025-06-30 05:59:35.369577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558c582c12c9'
down_revision = '9ed064cdf4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('willing_to_mentor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('founder_interests', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('investor_interests', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('investor_interests')
        batch_op.drop_column('founder_interests')
        batch_op.drop_column('willing_to_mentor')

    # ### end Alembic commands ###
