"""Add recall and deleted flags with default values

Revision ID: 9ed064cdf4f6
Revises: a97ec23ce5e9
Create Date: 2025-06-26 14:38:43.837873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed064cdf4f6'
down_revision = 'a97ec23ce5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_user_1', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('deleted_by_user_2', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recalled', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('edited_at')
        batch_op.drop_column('is_recalled')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('deleted_by_user_2')
        batch_op.drop_column('deleted_by_user_1')

    # ### end Alembic commands ###
